apiVersion: v1
kind: ConfigMap
metadata:
  name: "api-service-{{ .Values.api.configmap.stage }}"
  namespace: {{ .Values.ENV_NAMESPACE | quote }}
data:
  config.conf: |

    JWT_SECRET = "{{ .Values.secrets.server.jwt_secret }}"

    [Namespace]
    NAMESPACE = "{{ .Values.ENV_NAMESPACE }}"

    [Cache]
    REDIS_HOST = "{{ .Values.redis.redis_host }}"
    REDIS_PASS = "{{ .Values.secrets.redis.password }}"
    REDIS_PORT = "{{ .Values.redis.ports.targetPort }}"


    [Staging]

    STAGING_ENDPOINT_SUBDOMAIN = "{{ .Values.STAGING_ENDPOINT_SUBDOMAIN }}"
    STAGING_ENDPOINT_STAGE = "{{ .Values.STAGING_ENDPOINT_STAGE }}"
    DOMAIN_NAME = {{ .Values.DOMAIN_NAME }}

    [Broker]
    KAFKA_HOST = "{{ .Values.broker.kafkaHost }}"
    KAFKA_PORT = "{{ .Values.broker.kafkaPort }}"
    ZOOKEEPER_HOST = "{{ .Values.broker.zookeeperHost }}"
    ZOOKEEPER_PORT = "{{ .Values.broker.zookeeperPort }}"

    [Database]
    MONGODB_HOST =  "{{ .Values.mongodb.host }}"
    MONGODB_PORT = "{{ .Values.mongodb.port }}"
    MONGODB_DATABASE = "{{ .Values.mongodb.name }}"
    MONGODB_USER = "{{ .Values.mongodb.user }}"
    MONGODB_PASSWORD = "{{ .Values.mongodb.password }}"
