#apiVersion: authentication.istio.io/v1alpha1
#kind: Policy
#metadata:
#  name: default
#  namespace: openfaas
#spec:
#  peers:
#    - mtls: {}
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: default
#  namespace: openfaas
#spec:
#  host: "*.openfaas.svc.cluster.local"
#  trafficPolicy:
#    tls:
#      mode: ISTIO_MUTUAL
