{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}
{{- if .Values.istio.mtls -}}
# enforce mTLS to openfaas control plane
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: default
    namespace: {{ .Release.Namespace }}
spec:
    mtls:
        mode: STRICT
---
# enforce mTLS to openfaas control plane
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: default
    namespace: {{ .Release.Namespace }}
spec:
    host: "*.{{ .Release.Namespace }}.svc.cluster.local"
    trafficPolicy:
        tls:
            mode: ISTIO_MUTUAL
---
# enforce mTLS to functions
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
    name: default
    namespace: {{ $functionNs }}
spec:
    mtls:
        mode: STRICT
---
# enforce mTLS to functions
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: default
    namespace: {{ $functionNs | quote }}
spec:
    host: "*.{{ $functionNs }}.svc.cluster.local"
    trafficPolicy:
        tls:
            mode: ISTIO_MUTUAL
---
# disable mTLS to nats, the nats protocol is not supported by Istio
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: "nats-no-mtls"
    namespace: {{ .Release.Namespace }}
spec:
    host: "nats.{{ .Release.Namespace }}.svc.cluster.local"
    trafficPolicy:
        tls:
            mode: DISABLE
{{- end -}}
