
ARG NODE_ENV
ARG SERVICE_NAME

FROM ubuntu:18.04
RUN apt-get update

RUN apt-get install vim curl gcc sudo git make jq  -yq

RUN apt-get update --fix-missing
RUN sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -yq
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN echo \
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN sudo apt-get update
RUN sudo apt-get install docker-ce-cli -yq

WORKDIR "/app"
ENV USER=default

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt-get install nodejs -yq
RUN npm install -g yarn
WORKDIR "/app"
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install
COPY . .

################### ENVs ################
ENV NODE_ENV=${NODE_ENV}
ENV SERVICE_NAME=${SERVICE_NAME}
#########################################

CMD ["npm", "run", "start"]
