apiVersion: v1
kind: ConfigMap
metadata:
  name: "worker-provisioner-{{ .Values.worker.provisioner.configmap.stage }}"
  namespace: {{ .Values.ENV_NAMESPACE | quote }}
data:
  config.conf: |

    [Namespace]
    NAMESPACE = "{{ .Values.ENV_NAMESPACE }}"

    [Staging]

    STAGING_ENDPOINT_SUBDOMAIN = "{{ .Values.ENV_NAMESPACE }}-{{ .Values.STAGING_ENDPOINT_SUBDOMAIN }}"
    STAGING_ENDPOINT_STAGE = "{{ .Values.STAGING_ENDPOINT_STAGE }}"
    DOMAIN_NAME = {{ .Values.DOMAIN_NAME }}

    [Cache]
    REDIS_HOST = "{{ .Values.redis.redis_host }}"
    REDIS_PASS = "{{ .Values.secrets.redis.password }}"
    REDIS_PORT = "{{ .Values.redis.ports.targetPort }}"


    [Openfaas]
    OPENFAAS_HOST = "{{ .Values.openfaas.host }}"
    OPENFAAS_PORT = "{{ .Values.openfaas.port }}"

    [Broker]
    KAFKA_HOST = "{{ .Values.broker.kafkaHost }}"
    KAFKA_PORT = "{{ .Values.broker.kafkaPort }}"
    ZOOKEEPER_HOST = "{{ .Values.broker.zookeeperHost }}"
    ZOOKEEPER_PORT = "{{ .Values.broker.zookeeperPort }}"

    PROVISIONER_TOPIC = "{{ .Values.ENV_NAMESPACE }}-{{ .Values.worker.provisioner.kafka_topic }}"
    PROVISIONER_LOGSTREAM_TOPIC = "{{ .Values.ENV_NAMESPACE }}-{{ .Values.worker.provisioner.kafka_topic_logstream }}"

