kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: resource-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "pods", "deployments"]
    verbs: ["get", "watch", "list"]
