// @flow

export const EnvVars = {
    APP_VERSION: 'APP_VERSION',
    NODE_ENV: 'NODE_ENV',

    /*
    ########################################################################################
    ## THE KEYS BELOW MUST BE PROVIDED BY DEPLOYMENT ENV VARS AND IAM PARAMETER STORE ##
    ########################################################################################
    */

    JWT_SECRET: 'JWT_SECRET',
    DOMAIN_NAME: 'DOMAIN_NAME',


    DB_HOST: 'MONGODB_HOST',
    DB_USER: 'MONGODB_USER',
    DB_PASS: 'MONGODB_PASSWORD',
    DB_PORT: 'MONGODB_PORT',
    DB_NAME: 'MONGODB_DATABASE',

    REDIS_HOST: 'REDIS_HOST',
    REDIS_PASS: 'REDIS_PASS',
    REDIS_PORT: 'REDIS_PORT',
    REDIS_ADDRESS: 'REDIS_ADDRESS',

    ZOOKEEPER_HOST: 'ZOOKEEPER_HOST',
    ZOOKEEPER_PORT: 'ZOOKEEPER_PORT',

    KAFKA_HOST: 'KAFKA_HOST',
    KAFKA_PORT: 'KAFKA_PORT',

    OPENFAAS_HOST: 'OPENFAAS_HOST',
    OPENFAAS_PORT: 'OPENFAAS_PORT',

    PROVISIONER_SERVICE_URL: 'PROVISIONER_SERVICE_URL',
    PROVISIONER_SERVICE_PORT: 'PROVISIONER_SERVICE_PORT',

    NAMESPACE: 'NAMESPACE',

    USER_SERVICE_URL: 'USER_SERVICE_URL',
    USER_SERVICE_PORT: 'USER_SERVICE_PORT',
    USER_TOPIC: 'USER_TOPIC',

    AUTH_SERVICE_URL: 'AUTH_SERVICE_URL',
    AUTH_SERVICE_PORT: 'AUTH_SERVICE_PORT',

    PROVISIONER_TOPIC: 'PROVISIONER_TOPIC',
    PROVISIONER_LOGSTREAM_TOPIC: 'PROVISIONER_LOGSTREAM_TOPIC',

};

export type EnvVar = $Keys<typeof EnvVars>;
